name: Ing
channels:
  - defaults
dependencies:
  - python>3.8.0
  - pip>20.0.0
  - fastapi==0.75.2
  - loguru==0.5.3
  - matplotlib==3.1.3
  - numpy==1.21.6
  - pandas==1.2.3
  - pydantic==1.8.2
  - scikit_learn==1.0.2
  - tensorflow_data_validation==1.7.0
  - tqdm==4.46.1
  - uvicorn==0.15.0
